# Generated by Django 3.0.4 on 2020-07-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=20)),
                ('birthday', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
